
services:
  postgres:
    image: postgres:16
    container_name: skillhub_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stolenDev.to
      POSTGRES_DB: skillhub
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: skillhub_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@skillhub.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - skillhub-network
  app:
    build: .
    image: skill-hub
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env.production
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432

volumes:
  pgdata:
    name: skillhub

